# Global Mysql、Redis and RabbitMQ connect configuration items
common:
  rabbitmq:
#    host: 106.60.78.185
    host: 127.0.0.1
    username: admin
    password: 123456
    port: 5672
  redis:
#    host: 106.60.78.185
    host: 127.0.0.1
    password: 123456
    port: 6379
  mysql:
    primary:
      username: studio
      password: admin
      url: jdbc:mysql://106.60.78.185:3306/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    master:
      username: studio
      password: admin
      url: jdbc:p6spy:mysql://106.60.78.185:3306/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    flowable:
      username: studio
      password: admin
      url: jdbc:mysql://106.60.78.185:3306/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    quartz:
      username: studio
      password: admin
      url: jdbc:mysql://106.60.78.185:3306/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    druid:
      username: studio
      password: admin
      url: jdbc:mysql://106.60.78.185:3306/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    dts:
      driver-class-name: com.mysql.jdbc.Driver
      username: studio
      password: admin
      url: jdbc:mysql://106.60.78.185:3306/studio?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
